services:
  exb:
    build: .
    image: arcgis-exb-115:115
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      # Volume for the apps directory
      - ./apps:/usr/src/app/ArcGISExperienceBuilder/server/public/apps

      # Volume for user-added client data
      # TODO: cached for optimized mounting (due to issues with file watcher, triggering the TS compile process).. does it work?
      - ./client:/usr/src/app/ArcGISExperienceBuilder/client:cached
