services:
  webapp:
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./ArcGISExperienceBuilder/client:/usr/src/app/ArcGISExperienceBuilder/client
      - ./ArcGISExperienceBuilder/server/public/apps:/usr/src/app/ArcGISExperienceBuilder/server/public/apps
    env_file:
      - .env
