services:
  exb:
    # image: your_image_name:your_tag  # Reference the pre-built image
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      # Volume for the apps directory
      - ./apps:/usr/src/app/ArcGISExperienceBuilder/server/public/apps

      # Volume for user-added client data
      - ./client:/usr/src/app/ArcGISExperienceBuilder/client
